name: Deploy Docs to GitHub Pages with Catalog Builder Tool

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'docs/**'
      - 'src/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
  
    # Setup MingW32 cross compiler
    - name: Setup MingW32 cross compiler
      run: sudo apt update && sudo apt-get -y install mingw-w64

    # Setup .NET Core SDK
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Build Catalog Builder tool
    - name: Build Catalog Builder Tool
      run: dotnet build src/TableCloth.CatalogBuilder/TableCloth.CatalogBuilder.csproj --configuration Release

    # Run Catalog Builder tool
    - name: Run Catalog Builder Tool
      run: dotnet run --project src/TableCloth.CatalogBuilder/TableCloth.CatalogBuilder.csproj --configuration Release -- ./docs/ ./outputs/

    # Build Win32 Icon Library DLL
    - name: Build Win32 Icon Library DLL
      run: |
        /usr/bin/x86_64-w64-mingw32-windres -i ./outputs/Catalog.rc -o ./outputs/Catalog.o
        /usr/bin/x86_64-w64-mingw32-gcc -shared -mwindows -L -lcreate -o ./outputs/Catalog.dll ./outputs/Catalog.o
        rm ./outputs/Catalog.rc
        rm ./outputs/Catalog.o

    # Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./outputs
        publish_branch: gh-pages
